artifacts_root : artfacts 

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url: https://github.com/shrymhty/datasets/raw/main/samsum-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir : artfacts/data_validation