artifacts_root : artifacts 

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url: https://github.com/shrymhty/datasets/raw/main/samsum-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/samsum_data

data_validation:
  root_dir : artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["test.json", "train.json", "val.json"]